import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure Google Gemini API
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if GEMINI_API_KEY and GEMINI_API_KEY != "your-gemini-api-key-here":
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-pro')
else:
    model = None


def generate_negotiation_letter(user_name, lender_name, loan_type, outstanding_amount, 
                                 suggested_settlement, monthly_income, monthly_expenses):
    """
    Generate a professional negotiation letter using Google Gemini AI.
    Falls back to rule-based template if API is unavailable.
    """
    
    # Calculate debt-to-income ratio for context
    dti_ratio = ((monthly_expenses) / monthly_income * 100) if monthly_income > 0 else 0
    
    prompt = f"""
    Act as a professional financial negotiator and debt counselor. Write a formal, 
    empathetic, and persuasive settlement negotiation letter with the following details:
    
    **Borrower Information:**
    - Name: {user_name}
    - Monthly Income: ${monthly_income}
    - Monthly Expenses: ${monthly_expenses}
    - Debt-to-Income Ratio: {dti_ratio:.1f}%
    
    **Loan Details:**
    - Lender: {lender_name}
    - Loan Type: {loan_type}
    - Outstanding Amount: ${outstanding_amount:,.2f}
    - Proposed Settlement Amount: ${suggested_settlement:,.2f}
    
    The letter should:
    1. Be professional and respectful in tone
    2. Explain the borrower's financial hardship situation
    3. Clearly state the settlement offer
    4. Request a No Dues Certificate upon settlement
    5. Include a reasonable justification for the settlement amount
    6. Be formatted as a formal business letter
    7. Keep it concise (300-400 words)
    
    Write the complete negotiation letter.
    """
    
    try:
        if model:
            # Try to generate using Google Gemini AI
            response = model.generate_content(prompt)
            return response.text
        else:
            raise Exception("Gemini API key not configured")
            
    except Exception as e:
        print(f"AI Generation failed: {e}. Using fallback template...")
        # Use rule-based fallback
        return generate_fallback_letter(user_name, lender_name, loan_type, 
                                        outstanding_amount, suggested_settlement)


def generate_fallback_letter(user_name, lender_name, loan_type, 
                             outstanding_amount, suggested_settlement):
    """
    Rule-based fallback negotiation letter generator.
    Used when Gemini API is unavailable.
    """
    
    # Calculate settlement percentage
    settlement_percentage = ((suggested_settlement / outstanding_amount) * 100) if outstanding_amount > 0 else 0
    
    letter = f"""
Subject: Settlement Proposal for {loan_type} Loan Account - {user_name}

Dear {lender_name} Management,

I hope this letter finds you well. I am writing to formally propose a settlement 
for my {loan_type} loan account.

**Current Loan Status:**
- Outstanding Balance: ${outstanding_amount:,.2f}
- Proposed Settlement Amount: ${suggested_settlement:,.2f}
- Settlement Percentage: {settlement_percentage:.0f}%

Due to unforeseen financial circumstances, I am currently unable to repay the 
full outstanding amount. However, I am committed to resolving this debt responsibly 
and would like to propose a one-time lump sum settlement of ${suggested_settlement:,.2f}.

**Reasons for Settlement Request:**
1. Financial hardship affecting my repayment capacity
2. Desire to resolve the debt amicably and promptly
3. Ability to arrange the proposed settlement amount

**Settlement Terms Requested:**
- One-time payment of ${suggested_settlement:,.2f} as full and final settlement
- Issuance of No Dues Certificate upon payment
- Update credit bureau records to reflect "Settled" status
- Waiver of any additional penalties or charges

I believe this proposal is in the mutual interest of both parties as it ensures 
prompt recovery while providing me relief from financial stress.

I request you to kindly consider this proposal favorably and provide your written 
confirmation at the earliest. I am available for discussion if needed.

Thank you for your understanding and cooperation.

Sincerely,
{user_name}
Date: {__import__('datetime').datetime.now().strftime('%B %d, %Y')}

---
Note: This is an automated negotiation letter generated by FinRelief AI platform.
"""
    
    return letter


def analyze_financial_profile(monthly_income, monthly_expenses, total_debt):
    """
    Analyze borrower's financial profile and provide AI-powered recommendations.
    """
    
    surplus = monthly_income - monthly_expenses
    debt_to_income = (total_debt / monthly_income * 100) if monthly_income > 0 else 0
    
    prompt = f"""
    Analyze this borrower's financial situation and provide recommendations:
    
    - Monthly Income: ${monthly_income}
    - Monthly Expenses: ${monthly_expenses}
    - Total Debt: ${total_debt}
    - Monthly Surplus: ${surplus}
    - Debt-to-Income Ratio: {debt_to_income:.1f}%
    
    Provide:
    1. Financial health assessment (2-3 sentences)
    2. Repayment capacity analysis
    3. Recommended debt management strategy
    4. Timeline suggestion for debt resolution
    
    Keep it concise and professional.
    """
    
    try:
        if model:
            response = model.generate_content(prompt)
            return response.text
        else:
            return generate_fallback_analysis(surplus, debt_to_income)
    except Exception:
        return generate_fallback_analysis(surplus, debt_to_income)


def generate_fallback_analysis(surplus, debt_to_income):
    """
    Rule-based financial analysis fallback.
    """
    
    if surplus > 0 and debt_to_income < 40:
        health = "Good"
        strategy = "Continue regular payments while building emergency fund"
    elif surplus > 0 and debt_to_income < 60:
        health = "Moderate"
        strategy = "Consider debt consolidation or settlement negotiation"
    else:
        health = "Stressed"
        strategy = "Immediate settlement negotiation recommended"
    
    return f"""
Financial Health Assessment: {health}

Analysis:
- Monthly Surplus: ${surplus:.2f}
- Debt-to-Income Ratio: {debt_to_income:.1f}%

Recommendation:
{strategy}

Priority: Focus on high-interest loans first and negotiate settlements where possible.
"""